# Generated by Django 6.0.7 on 2026-07-26 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_seller_payout_sellerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', 'Fraud / Scam'), ('counterfeit', 'Counterfeit / Fake Product'), ('inappropriate', 'Inappropriate Content'), ('age_restricted', 'Age-Restricted Content (Underage)'), ('prohibited', 'Prohibited Item'), ('misleading', 'Misleading Description'), ('harassment', 'Harassment / Hate Speech'), ('spam', 'Spam / Fake Reviews'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='Please describe the issue in detail')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='products.product')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs More Information')], default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('business_type', models.CharField(choices=[('individual', 'Individual / Sole Proprietor'), ('company', 'Registered Company'), ('partnership', 'Partnership Firm')], default='individual', max_length=20)),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('business_reg_number', models.CharField(blank=True, default='', max_length=100)),
                ('pan_number', models.CharField(blank=True, default='', max_length=20)),
                ('business_description', models.TextField(blank=True, default='')),
                ('selling_reason', models.TextField(help_text='Why do you want to sell on Islington Marketplace?')),
                ('estimated_monthly_sales', models.CharField(blank=True, default='', max_length=50)),
                ('date_of_birth', models.DateField(help_text='Required for age-restricted categories')),
                ('is_age_verified', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('citizenship', 'Citizenship Certificate'), ('passport', 'Passport'), ('license', 'Driving License'), ('national_id', 'National ID Card'), ('pan', 'PAN Card'), ('business_reg', 'Business Registration Certificate')], default='citizenship', max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('document_front', models.ImageField(blank=True, null=True, upload_to='seller_docs/front/')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='seller_docs/back/')),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('agreed_to_privacy', models.BooleanField(default=False)),
                ('agreed_to_seller_policy', models.BooleanField(default=False)),
                ('consent_to_data_processing', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_categories', models.ManyToManyField(blank=True, to='products.category')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
