# Generated by Django 6.0.7 on 2026-07-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_contentreport_sellerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Required for age-restricted categories', null=True),
        ),
    ]
