# Generated by Django 6.0.7 on 2026-07-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_sellerapplication_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('card', 'Credit/Debit Card')], default='cod', max_length=50),
        ),
    ]
